name: android
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.4+2
  razorpay_flutter: ^1.2.1
  permission_handler: ^3.0.0
  agora_rtc_engine: ^1.0.5
  intl: ^0.16.1
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  fluttertoast: ^4.0.1
  country_code_picker: ^1.4.0
  otp_text_field: ^1.0.1
  flutter_rating_bar: ^3.0.1+1
  smooth_star_rating: ^1.1.1
  material_design_icons_flutter: ^4.0.5345
  like_button: ^1.0.1
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/facebook-logo.png
   - assets/images/google-logo.png
   - assets/images/mentee_icon.png
   - assets/images/mentees.png
   - assets/images/payments.png
   - assets/images/profile.png
   - assets/images/profile2.png
   - assets/images/profile3.png
   - assets/images/reviews.png
   - assets/images/schedule.png
   - assets/images/empty_user.jpg
   - assets/images/vorby/black_bg.png
   - assets/images/vorby/no_bg.png
   - assets/images/vorby/white_bg.png
   - assets/images/gpay.png
   - assets/images/upi.png
   - assets/images/phonepe.png
  fonts:
    - family: Literal
      fonts:
        - asset: assets/fonts/Literal/Literal-Regular.ttf
        - asset: assets/fonts/Literal/Literal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Literal/Literal-Light.ttf
          weight: 300
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
